# Generated by Django 3.1.2 on 2020-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
