# Generated by Django 3.1.2 on 2020-10-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20201027_1442'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='Registration',
        ),
    ]
