# Generated by Django 3.1.2 on 2020-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20201029_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='company_id',
            field=models.EmailField(max_length=50),
        ),
    ]
